"""empty message

Revision ID: ce94e8fb7cf9
Revises: 
Create Date: 2025-10-15 13:51:27.150258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ce94e8fb7cf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingparameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Enum('LSTM', 'GRU', 'BiLSTM', 'TCN', 'Transformer', 'Transformer_KAN', 'BP', 'Autoformer', name='model_type'), nullable=False),
    sa.Column('hidden_size', sa.Integer(), nullable=True),
    sa.Column('num_layers', sa.Integer(), nullable=True),
    sa.Column('dropout', sa.Float(), nullable=True),
    sa.Column('grid_size', sa.Integer(), nullable=True),
    sa.Column('num_channels', sa.String(length=50), nullable=True),
    sa.Column('kernel_size', sa.Integer(), nullable=True),
    sa.Column('num_heads', sa.Integer(), nullable=True),
    sa.Column('hidden_space', sa.Integer(), nullable=True),
    sa.Column('e_layers', sa.Integer(), nullable=True),
    sa.Column('d_ff', sa.Integer(), nullable=True),
    sa.Column('moving_avg', sa.Integer(), nullable=True),
    sa.Column('factor', sa.Integer(), nullable=True),
    sa.Column('activation', sa.Enum('relu', 'leaky_relu', 'elu', 'gelu', 'sigmoid', 'tanh', 'softplus', 'silu', 'none', name='act_type'), nullable=False),
    sa.Column('use_layer_norm', sa.Boolean(), nullable=True),
    sa.Column('num_epochs', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('loss', sa.Enum('mse', 'mae', 'huber', 'smooth_l1', 'log_cosh', 'quantile', 'mape', 'smape', name='loss_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['directories.id'], ),
    sa.ForeignKeyConstraint(['root_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lossimagemodel',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True, comment='图片文件名，用于区分'),
    sa.Column('file_path', sa.String(length=512), nullable=True, comment='图片文件路径'),
    sa.Column('trainname', sa.String(length=100), nullable=True, comment='模型名'),
    sa.Column('trainepoch_path', sa.String(length=512), nullable=True, comment='训练周期数据文件路径'),
    sa.Column('zxl_loss', sa.String(length=100), nullable=True, comment='总训练损失'),
    sa.Column('zyz_loss', sa.String(length=100), nullable=True, comment='总验证损失'),
    sa.Column('modelname', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=False, comment='图片所属批次（第几批）'),
    sa.Column('training_params_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_params_id'], ['trainingparameters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_params_id')
    )
    op.create_table('smartformula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True, comment='预测对比图文件名，用于区分'),
    sa.Column('file_path', sa.String(length=512), nullable=True, comment='预测对比图文件路径'),
    sa.Column('formula_name', sa.String(length=100), nullable=True, comment='公式图片文件名，用于区分'),
    sa.Column('formula_path', sa.String(length=512), nullable=True, comment='公式图片文件路径'),
    sa.Column('coordinate', sqlite.JSON(), nullable=True, comment='真实值与预测值坐标数据'),
    sa.Column('index', sa.String(length=255), nullable=True),
    sa.Column('complexity', sa.String(length=255), nullable=True),
    sa.Column('loss', sa.String(length=255), nullable=True),
    sa.Column('score', sa.String(length=255), nullable=True),
    sa.Column('r2', sa.String(length=255), nullable=True),
    sa.Column('mae', sa.String(length=255), nullable=True),
    sa.Column('mse', sa.String(length=255), nullable=True),
    sa.Column('rmse', sa.String(length=255), nullable=True),
    sa.Column('latex', sa.String(length=255), nullable=True),
    sa.Column('indexb', sa.String(length=255), nullable=True),
    sa.Column('complexityb', sa.String(length=255), nullable=True),
    sa.Column('lossb', sa.String(length=255), nullable=True),
    sa.Column('scoreb', sa.String(length=255), nullable=True),
    sa.Column('r2b', sa.String(length=255), nullable=True),
    sa.Column('maeb', sa.String(length=255), nullable=True),
    sa.Column('mseb', sa.String(length=255), nullable=True),
    sa.Column('rmseb', sa.String(length=255), nullable=True),
    sa.Column('latexb', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=False, comment='图片所属批次（第几批）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('config_params', sqlite.JSON(), nullable=True, comment='前端传来的完整配置参数（JSON格式）'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True, comment='存放文件名'),
    sa.Column('trainepoch_path', sa.String(length=512), nullable=True, comment='训练周期数据文件路径'),
    sa.Column('avg_val_loss', sa.String(length=100), nullable=True, comment='存放损失'),
    sa.Column('avg_train_loss', sa.String(length=100), nullable=True, comment='存放损失'),
    sa.Column('filepicture_name', sa.String(length=100), nullable=True, comment='存放损失图片名'),
    sa.Column('filepicture_path', sa.String(length=512), nullable=True, comment='损失图片文件路径'),
    sa.Column('modelname', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=False, comment='模型所属批次（第几批）'),
    sa.Column('training_params_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_params_id'], ['trainingparameters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_params_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('xlsx', 'txt', name='file_type'), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['directory_id'], ['directories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_file_hash'), ['file_hash'], unique=False)

    op.create_table('errtabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('MSE', sa.Float(), nullable=True),
    sa.Column('MAE', sa.Float(), nullable=True),
    sa.Column('RMSE', sa.Float(), nullable=True),
    sa.Column('R2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_table('model_config',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Enum('LSTM', 'GRU', 'BiLSTM', 'TCN', 'Transformer', 'Transformer_KAN', 'BP', 'Autoformer', name='model_type'), nullable=False),
    sa.Column('hidden_size', sa.Integer(), nullable=True),
    sa.Column('num_layers', sa.Integer(), nullable=True),
    sa.Column('dropout', sa.Float(), nullable=True),
    sa.Column('grid_size', sa.Integer(), nullable=True),
    sa.Column('num_channels', sa.String(length=50), nullable=True),
    sa.Column('kernel_size', sa.Integer(), nullable=True),
    sa.Column('num_heads', sa.Integer(), nullable=True),
    sa.Column('hidden_space', sa.Integer(), nullable=True),
    sa.Column('e_layers', sa.Integer(), nullable=True),
    sa.Column('d_ff', sa.Integer(), nullable=True),
    sa.Column('moving_avg', sa.Integer(), nullable=True),
    sa.Column('factor', sa.Integer(), nullable=True),
    sa.Column('activation', sa.Enum('relu', 'leaky_relu', 'elu', 'gelu', 'sigmoid', 'tanh', 'softplus', 'silu', 'none', name='act_type'), nullable=False),
    sa.Column('use_layer_norm', sa.Boolean(), nullable=True),
    sa.Column('seq_len', sa.Integer(), nullable=True),
    sa.Column('num_epochs', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('input_directory', sa.String(length=255), nullable=True),
    sa.Column('predict_target', sa.String(length=50), nullable=True),
    sa.Column('input_size', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('output_size', sa.Integer(), nullable=True),
    sa.Column('sequence_length', sa.Integer(), nullable=True),
    sa.Column('scaler_type', sa.Enum('minmax', 'standard', 'robust', name='sca_type'), nullable=True),
    sa.Column('loss', sa.Enum('mse', 'mae', 'huber', 'smooth_l1', 'log_cosh', 'quantile', 'mape', 'smape', name='loss_type'), nullable=False),
    sa.Column('phy_equation', sa.Text(), nullable=True),
    sa.Column('phy_loss_type', sa.Enum('mse', 'mae', name='phy_loss_type'), nullable=False),
    sa.Column('phy_loss_weight', sa.Float(), nullable=True),
    sa.Column('phy_loss_lower', sa.Float(), nullable=True),
    sa.Column('phy_loss_upper', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('trainloaderpkl', sa.String(length=512), nullable=True),
    sa.Column('valloaderpkl', sa.String(length=512), nullable=True),
    sa.Column('xpkl', sa.String(length=512), nullable=True),
    sa.Column('ypkl', sa.String(length=512), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('dad_id', sa.Integer(), nullable=True),
    sa.Column('original_file_id', sa.Integer(), nullable=True, comment='用户最初处理的原始文件ID，关联file表'),
    sa.ForeignKeyConstraint(['dad_id'], ['directories.id'], ),
    sa.ForeignKeyConstraint(['original_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_config')
    op.drop_table('errtabs')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_file_hash'))

    op.drop_table('files')
    op.drop_table('trainmodel')
    op.drop_table('smartformula')
    op.drop_table('lossimagemodel')
    op.drop_table('directories')
    op.drop_table('users')
    op.drop_table('trainingparameters')
    # ### end Alembic commands ###
